### ISSUE TITLE
yarp network no longer connecting

### ISSUE THREAD

**Issue by vtikha** [francesco-romano/iYarp#4]
@francesco-romano, it seems that the app does not open the ports anymore and the debugging output is:

```
yarp: YARP not initialized; create a yarp::os::Network object before using ports
warning: YARP name server(s) not configured, ports will be anonymous
warning: check your namespace and settings with 'yarp detect'
2015-09-24 11:41:29.739 IOL[674:159766] Yarp network successful initialized 
```

**Comment by francesco-romano** [comment]
Now I remember.
When the app starts, it checks the yarp network. 
Unfortunately, in order to do the animation in the fastest way possible the first view is created anyway.
And now we moved the creation of the port in the view constructor.

**Comment by vtikha** [comment]
Indeed you are right! :+1:
